### ISSUE TITLE
where to add google credentials

### ISSUE THREAD

**Issue by vivekkanaujiyaaa** [dhaval-mehta/url-to-google-drive#5] opened 2018-06-17 11:00 UTC
hey i have the google authentication credential but i cannot understand where to add in the scrip please help

**Comment by dhaval-mehta** [comment] 2018-07-05 18:51
It is duplicate of https://github.com/dhaval-mehta/url-to-google-drive/issues/4

**Closed by dhaval-mehta** 2018-07-05 18:51 UTC
Labels: duplicate, help wanted
